"""
Film stock definitions — comprehensive curated collection.
Lazy initialization: conversions are built on first use, not at import.
"""

import numpy as np
import spectral_film_lut as sfl
from core.conversion import make_conversion

CATEGORIES = {
    "pro_color": "Pro Color",
    "consumer": "Consumer",
    "cinema": "Cinema",
    "vintage_cinema": "Vintage Cinema",
    "bw": "B&W",
    "reversal": "Slide Film",
    "instant": "Instant & Experimental",
}

# Stock definitions — conversion built lazily on first access
_STOCK_DEFS = {
    # ── Pro Color Negative ──────────────────────────────────────────────
    "portra160": {
        "name": "Kodak Portra 160",
        "category": "pro_color",
        "description": "Finest grain Portra, soft pastels, wedding favorite",
        "neg_data": sfl.KODAK_PORTRA_160,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.3, "sat": 1.0,
        # Portra 160: very open shadows, slight warmth, soft highlight compression
        "pre_flash_neg": -2.5, "black_offset": 1.5, "white_point": 0.94, "tint": 0,
        "halation_strength": 0.12, "halation_radius": 0.05,
        "halation_color": np.array([0.15, 0.30, 0.90]),
        "halation_threshold": 0.68,
        "vignette": 0.25, "bloom": 0.08,
        "border_text": "KODAK  5052  PORTRA 160",
        "film_format_mm": 35,
    },
    "portra400": {
        "name": "Kodak Portra 400",
        "category": "pro_color",
        "description": "The gold standard — warm skin, pastel highlights, lifted shadows",
        "neg_data": sfl.KODAK_PORTRA_400,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.35, "sat": 1.0,
        # Portra 400: THE portrait film — lifted shadows, pastel color, warm
        "pre_flash_neg": -2.2, "black_offset": 2.0, "white_point": 0.93, "tint": 0,
        "halation_strength": 0.15, "halation_radius": 0.06,
        "halation_color": np.array([0.15, 0.30, 0.95]),
        "halation_threshold": 0.65,
        "vignette": 0.30, "bloom": 0.10,
        "border_text": "KODAK  5054  PORTRA 400",
        "film_format_mm": 35,
    },
    "portra800": {
        "name": "Kodak Portra 800",
        "category": "pro_color",
        "description": "Pushed Portra — more grain, more contrast, low light king",
        "neg_data": sfl.KODAK_PORTRA_800,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.45, "sat": 1.02,
        # Portra 800: grittier Portra, more contrast, still warm shadows
        "pre_flash_neg": -2.5, "black_offset": 1.0, "white_point": 0.92, "tint": 0,
        "halation_strength": 0.18, "halation_radius": 0.07,
        "halation_color": np.array([0.15, 0.28, 0.95]),
        "halation_threshold": 0.62,
        "vignette": 0.32, "bloom": 0.12,
        "border_text": "KODAK  5056  PORTRA 800",
        "film_format_mm": 35,
    },
    "fuji400h": {
        "name": "Fuji Pro 400H",
        "category": "pro_color",
        "description": "Cool greens, airy highlights — the other portrait film",
        "neg_data": sfl.FUJI_PRO_400H,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.25, "sat": 1.0,
        # Fuji 400H: cool/green shadows, airy highlight rendering
        "pre_flash_neg": -2.5, "black_offset": 1.5, "white_point": 0.94, "tint": 0,
        "halation_strength": 0.10, "halation_radius": 0.05,
        "halation_color": np.array([0.20, 0.35, 0.85]),
        "halation_threshold": 0.68,
        "vignette": 0.25, "bloom": 0.08,
        "border_text": "FUJI  PRO 400H",
        "film_format_mm": 35,
    },
    "fuji160c": {
        "name": "Fuji Pro 160C",
        "category": "pro_color",
        "description": "Cool tones, fine grain — fashion and editorial",
        "neg_data": sfl.FUJI_PRO_160C,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.2, "sat": 1.0,
        "halation_strength": 0.10, "halation_radius": 0.04,
        "halation_color": np.array([0.18, 0.32, 0.88]),
        "halation_threshold": 0.70,
        "vignette": 0.22, "bloom": 0.06,
        "border_text": "FUJI  PRO 160C",
        "film_format_mm": 35,
    },
    "ektar100": {
        "name": "Kodak Ektar 100",
        "category": "pro_color",
        "description": "Ultra-saturated, finest grain color neg — landscape king",
        "neg_data": sfl.KODAK_EKTAR_100,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.2, "sat": 1.12,
        # Ektar: MAXIMUM saturation color neg, punchy, tight blacks
        "pre_flash_neg": -3.2, "black_offset": -0.3, "white_point": 0.97, "tint": 0,
        "halation_strength": 0.10, "halation_radius": 0.04,
        "halation_color": np.array([0.12, 0.28, 0.92]),
        "halation_threshold": 0.70,
        "vignette": 0.25, "bloom": 0.06,
        "border_text": "KODAK  EKTAR 100",
        "film_format_mm": 35,
    },
    "fuji160s": {
        "name": "Fuji Pro 160S",
        "category": "pro_color",
        "description": "Smooth, neutral — studio portrait workhorse",
        "neg_data": sfl.FUJI_PRO_160S,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.2, "sat": 1.0,
        "halation_strength": 0.10, "halation_radius": 0.04,
        "halation_color": np.array([0.18, 0.32, 0.88]),
        "halation_threshold": 0.70,
        "vignette": 0.22, "bloom": 0.06,
        "border_text": "FUJI  PRO 160S",
        "film_format_mm": 35,
    },
    "portra800_1600": {
        "name": "Portra 800 @ 1600",
        "category": "pro_color",
        "description": "1-stop push — contrasty, gritty, concert/club vibes",
        "neg_data": sfl.KODAK_PORTRA_800_AT_1600,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.5, "sat": 1.02,
        "halation_strength": 0.20, "halation_radius": 0.08,
        "halation_color": np.array([0.14, 0.28, 0.95]),
        "halation_threshold": 0.58,
        "vignette": 0.35, "bloom": 0.14,
        "border_text": "KODAK  PORTRA 800  +1",
        "film_format_mm": 35,
    },
    "portra800_3200": {
        "name": "Portra 800 @ 3200",
        "category": "pro_color",
        "description": "2-stop push — extreme grain, crushed look, dark venues",
        "neg_data": sfl.KODAK_PORTRA_800_AT_3200,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.6, "sat": 1.0,
        "halation_strength": 0.22, "halation_radius": 0.09,
        "halation_color": np.array([0.14, 0.26, 0.95]),
        "halation_threshold": 0.55,
        "vignette": 0.38, "bloom": 0.16,
        "border_text": "KODAK  PORTRA 800  +2",
        "film_format_mm": 35,
    },
    "vericolor": {
        "name": "Kodak Vericolor III",
        "category": "pro_color",
        "description": "Discontinued legend — neutral, low saturation, Sears portrait studio",
        "neg_data": sfl.KODAK_VERICOLOR_III,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.2, "sat": 0.98,
        "halation_strength": 0.10, "halation_radius": 0.04,
        "halation_color": np.array([0.15, 0.30, 0.88]),
        "halation_threshold": 0.70,
        "vignette": 0.25, "bloom": 0.06,
        "border_text": "KODAK  VERICOLOR III",
        "film_format_mm": 35,
    },

    # ── Consumer Color ──────────────────────────────────────────────────
    "gold200": {
        "name": "Kodak Gold 200",
        "category": "consumer",
        "description": "Warm, punchy, saturated — the nostalgic consumer classic",
        "neg_data": sfl.KODAK_GOLD_200,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.35, "sat": 1.12,
        # Gold 200: WARM, punchy, saturated — the nostalgia stock
        "pre_flash_neg": -3.0, "black_offset": 0.5, "white_point": 0.96, "tint": 0,
        "halation_strength": 0.12, "halation_radius": 0.05,
        "halation_color": np.array([0.10, 0.30, 1.0]),
        "halation_threshold": 0.68,
        "vignette": 0.35, "bloom": 0.08,
        "border_text": "KODAK  GOLD 200",
        "film_format_mm": 35,
    },
    "ultramax400": {
        "name": "Kodak Ultramax 400",
        "category": "consumer",
        "description": "Punchy and versatile — drugstore hero",
        "neg_data": sfl.KODAK_ULTRAMAX_400,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.3, "sat": 1.10,
        # Ultramax: punchy consumer, strong warm bias, contrasty
        "pre_flash_neg": -3.2, "black_offset": -0.5, "white_point": 0.94, "tint": 0,
        "halation_strength": 0.14, "halation_radius": 0.06,
        "halation_color": np.array([0.12, 0.30, 0.95]),
        "halation_threshold": 0.65,
        "vignette": 0.35, "bloom": 0.10,
        "border_text": "KODAK  ULTRAMAX 400",
        "film_format_mm": 35,
    },
    "superia400": {
        "name": "Fuji Superia X-TRA 400",
        "category": "consumer",
        "description": "Iconic green cast, punchy — the Fuji disposable look",
        "neg_data": sfl.FUJI_SUPERIA_XTRA_400,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.2, "sat": 1.06,
        # Superia: GREEN shadow cast, punchy mids — the disposable camera look
        "pre_flash_neg": -3.2, "black_offset": 0.5, "white_point": 0.96, "tint": 0,
        "halation_strength": 0.12, "halation_radius": 0.05,
        "halation_color": np.array([0.15, 0.35, 0.90]),
        "halation_threshold": 0.68,
        "vignette": 0.35, "bloom": 0.08,
        "border_text": "FUJI  SUPERIA X-TRA 400",
        "film_format_mm": 35,
    },
    "fujic200": {
        "name": "Fuji C200",
        "category": "consumer",
        "description": "Budget classic — slightly cool, everyday snapshots",
        "neg_data": sfl.FUJI_C200,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.2, "sat": 1.02,
        "halation_strength": 0.10, "halation_radius": 0.05,
        "halation_color": np.array([0.18, 0.32, 0.88]),
        "halation_threshold": 0.70,
        "vignette": 0.30, "bloom": 0.06,
        "border_text": "FUJI  C200",
        "film_format_mm": 35,
    },
    "natura1600": {
        "name": "Fuji Natura 1600",
        "category": "consumer",
        "description": "High ISO party film — grainy, warm, nightlife vibes",
        "neg_data": sfl.FUJI_NATURA_1600,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.45, "sat": 1.02,
        # Natura 1600: grainy, warm, pushed look — Tokyo nightlife
        "pre_flash_neg": -2.5, "black_offset": 1.5, "white_point": 0.91, "tint": 0,
        "halation_strength": 0.18, "halation_radius": 0.07,
        "halation_color": np.array([0.15, 0.30, 0.92]),
        "halation_threshold": 0.60,
        "vignette": 0.35, "bloom": 0.14,
        "border_text": "FUJI  NATURA 1600",
        "film_format_mm": 35,
    },
    "agfavista100": {
        "name": "Agfa Vista 100",
        "category": "consumer",
        "description": "Warm European tones — discontinued cult favorite",
        "neg_data": sfl.AGFA_VISTA_100,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.2, "sat": 1.04,
        "halation_strength": 0.10, "halation_radius": 0.05,
        "halation_color": np.array([0.12, 0.28, 0.95]),
        "halation_threshold": 0.68,
        "vignette": 0.32, "bloom": 0.08,
        "border_text": "AGFA  VISTA 100",
        "film_format_mm": 35,
    },
    "superia_reala": {
        "name": "Fuji Superia Reala",
        "category": "consumer",
        "description": "4th color layer for accuracy — discontinued holy grail",
        "neg_data": sfl.FUJI_SUPERIA_REALA,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.2, "sat": 1.0,
        "halation_strength": 0.10, "halation_radius": 0.04,
        "halation_color": np.array([0.16, 0.32, 0.88]),
        "halation_threshold": 0.70,
        "vignette": 0.28, "bloom": 0.06,
        "border_text": "FUJI  SUPERIA REALA",
        "film_format_mm": 35,
    },
    # Gold 200 on Fuji paper — different look, warm neg + cool print
    "gold200_fuji": {
        "name": "Kodak Gold 200 (Fuji Print)",
        "category": "consumer",
        "description": "Gold on Fuji Crystal Archive — cross-lab recipe, cooler shadows",
        "neg_data": sfl.KODAK_GOLD_200,
        "print_data": sfl.FUJI_CA_DPII,
        "exposure_kelvin": 5500, "exp_comp": 0.2, "sat": 1.05,
        "halation_strength": 0.12, "halation_radius": 0.05,
        "halation_color": np.array([0.10, 0.30, 1.0]),
        "halation_threshold": 0.68,
        "vignette": 0.35, "bloom": 0.08,
        "border_text": "KODAK  GOLD 200  *FUJI",
        "film_format_mm": 35,
    },

    # ── Cinema ──────────────────────────────────────────────────────────
    "cinestill800t": {
        "name": "Cinestill 800T",
        "category": "cinema",
        "description": "Tungsten cinema — extreme red halation from removed remjet",
        "neg_data": sfl.KODAK_5219,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 3200, "exp_comp": 0.3, "sat": 1.04,
        # Cinestill 800T: crushed blue-teal blacks, warm highlights, extreme halation
        "pre_flash_neg": -3.5, "black_offset": -0.8, "white_point": 0.95, "tint": 0,
        "halation_strength": 0.60, "halation_radius": 0.12,
        "halation_color": np.array([0.02, 0.08, 1.0]),
        "halation_threshold": 0.40,
        "vignette": 0.28, "bloom": 0.18,
        "border_text": "CINESTILL  800T",
        "film_format_mm": 35,
    },
    "cinestill50d": {
        "name": "Cinestill 50D",
        "category": "cinema",
        "description": "Daylight cinema — fine grain, clean, with subtle halation",
        "neg_data": sfl.KODAK_5203,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.2, "sat": 1.02,
        # Cinestill 50D: clean daylight cinema, subtle halation, fine grain
        "pre_flash_neg": -3.5, "black_offset": -1.0, "white_point": 0.93, "tint": 0,
        "halation_strength": 0.35, "halation_radius": 0.08,
        "halation_color": np.array([0.05, 0.12, 1.0]),
        "halation_threshold": 0.50,
        "vignette": 0.25, "bloom": 0.10,
        "border_text": "CINESTILL  50D",
        "film_format_mm": 35,
    },
    "vision3_250d": {
        "name": "Kodak Vision3 250D",
        "category": "cinema",
        "description": "Mid-speed daylight cinema — balanced, versatile",
        "neg_data": sfl.KODAK_5207,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.25, "sat": 1.0,
        "halation_strength": 0.08, "halation_radius": 0.04,
        "halation_color": np.array([0.12, 0.25, 0.90]),
        "halation_threshold": 0.70,
        "vignette": 0.22, "bloom": 0.08,
        "border_text": "KODAK  5207  250D",
        "film_format_mm": 35,
    },
    "vision3_200t": {
        "name": "Kodak Vision3 200T",
        "category": "cinema",
        "description": "Tungsten cinema with remjet — no halation, clean tungsten look",
        "neg_data": sfl.KODAK_5213,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 3200, "exp_comp": 0.3, "sat": 1.0,
        "halation_strength": 0.06, "halation_radius": 0.03,
        "halation_color": np.array([0.12, 0.25, 0.88]),
        "halation_threshold": 0.72,
        "vignette": 0.22, "bloom": 0.08,
        "border_text": "KODAK  5213  200T",
        "film_format_mm": 35,
    },
    "eterna500": {
        "name": "Fuji Eterna 500",
        "category": "cinema",
        "description": "Fuji cinema stock — different color science than Kodak",
        "neg_data": sfl.FUJI_ETERNA_500,
        "print_data": sfl.FUJI_3513,
        "exposure_kelvin": 3200, "exp_comp": 0.3, "sat": 1.0,
        "halation_strength": 0.06, "halation_radius": 0.03,
        "halation_color": np.array([0.15, 0.28, 0.85]),
        "halation_threshold": 0.72,
        "vignette": 0.22, "bloom": 0.08,
        "border_text": "FUJI  ETERNA 500",
        "film_format_mm": 35,
    },
    "eterna_vivid": {
        "name": "Fuji Eterna Vivid 500",
        "category": "cinema",
        "description": "Punchier Fuji cinema — more saturation than standard Eterna",
        "neg_data": sfl.FUJI_ETERNA_500_VIVID,
        "print_data": sfl.FUJI_3513,
        "exposure_kelvin": 3200, "exp_comp": 0.3, "sat": 1.0,
        "halation_strength": 0.06, "halation_radius": 0.03,
        "halation_color": np.array([0.15, 0.28, 0.85]),
        "halation_threshold": 0.72,
        "vignette": 0.22, "bloom": 0.08,
        "border_text": "FUJI  ETERNA VIVID 500",
        "film_format_mm": 35,
    },
    "vision3_500t": {
        "name": "Kodak Vision3 500T",
        "category": "cinema",
        "description": "Fastest cinema stock — No Country, Sicario, Joker",
        "neg_data": sfl.KODAK_5219,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 3200, "exp_comp": 0.3, "sat": 1.0,
        "halation_strength": 0.06, "halation_radius": 0.03,
        "halation_color": np.array([0.12, 0.25, 0.88]),
        "halation_threshold": 0.72,
        "vignette": 0.22, "bloom": 0.08,
        "border_text": "KODAK  5219  500T",
        "film_format_mm": 35,
    },
    "vision3_50d": {
        "name": "Kodak Vision3 50D",
        "category": "cinema",
        "description": "Sharpest cinema stock — Barbie, La La Land daylight scenes",
        "neg_data": sfl.KODAK_5203,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.15, "sat": 1.0,
        "halation_strength": 0.05, "halation_radius": 0.03,
        "halation_color": np.array([0.12, 0.25, 0.90]),
        "halation_threshold": 0.72,
        "vignette": 0.20, "bloom": 0.06,
        "border_text": "KODAK  5203  50D",
        "film_format_mm": 35,
    },
    # Cinema on Fuji print — different look entirely
    "vision3_500t_fuji": {
        "name": "Vision3 500T (Fuji Print)",
        "category": "cinema",
        "description": "Kodak neg on Fuji print — cooler, bluer, Japanese cinema vibe",
        "neg_data": sfl.KODAK_5219,
        "print_data": sfl.FUJI_3513,
        "exposure_kelvin": 3200, "exp_comp": 0.3, "sat": 1.0,
        "halation_strength": 0.06, "halation_radius": 0.03,
        "halation_color": np.array([0.12, 0.25, 0.88]),
        "halation_threshold": 0.72,
        "vignette": 0.22, "bloom": 0.08,
        "border_text": "KODAK  5219  *FUJI PRINT",
        "film_format_mm": 35,
    },

    # ── Vintage Cinema (discontinued stocks) ────────────────────────────
    "5247": {
        "name": "Kodak 5247 (1970s)",
        "category": "vintage_cinema",
        "description": "The Godfather, Taxi Driver, Apocalypse Now — 70s cinema",
        "neg_data": sfl.KODAK_5247,
        "print_data": sfl.KODAK_5381,
        "exposure_kelvin": 3200, "exp_comp": 0.4, "sat": 1.0,
        # 5247 (70s): warm, lower saturation, lifted orange shadows — Godfather look
        "pre_flash_neg": -2.5, "black_offset": 2.0, "white_point": 0.90, "tint": 0,
        "halation_strength": 0.10, "halation_radius": 0.05,
        "halation_color": np.array([0.10, 0.25, 0.92]),
        "halation_threshold": 0.65,
        "vignette": 0.30, "bloom": 0.12,
        "border_text": "KODAK  5247",
        "film_format_mm": 35,
    },
    "5247ii": {
        "name": "Kodak 5247 II (1980s)",
        "category": "vintage_cinema",
        "description": "Blade Runner, ET, Empire Strikes Back — 80s blockbusters",
        "neg_data": sfl.KODAK_5247_II,
        "print_data": sfl.KODAK_5381,
        "exposure_kelvin": 3200, "exp_comp": 0.35, "sat": 1.02,
        # 5247 II (80s): slightly cleaner, still warm — Blade Runner, ET
        "pre_flash_neg": -2.8, "black_offset": 1.5, "white_point": 0.91, "tint": 0,
        "halation_strength": 0.10, "halation_radius": 0.05,
        "halation_color": np.array([0.10, 0.25, 0.90]),
        "halation_threshold": 0.65,
        "vignette": 0.28, "bloom": 0.10,
        "border_text": "KODAK  5247 II",
        "film_format_mm": 35,
    },
    "5248": {
        "name": "Kodak EXR 5248 (1990s)",
        "category": "vintage_cinema",
        "description": "Pulp Fiction, Forrest Gump, Fight Club — 90s look",
        "neg_data": sfl.KODAK_5248,
        "print_data": sfl.KODAK_5383,
        "exposure_kelvin": 3200, "exp_comp": 0.3, "sat": 1.0,
        # 5248 (90s): cooler than 70s/80s, more modern — Pulp Fiction, Fight Club
        "pre_flash_neg": -3.0, "black_offset": 0.5, "white_point": 0.93, "tint": 0,
        "halation_strength": 0.08, "halation_radius": 0.04,
        "halation_color": np.array([0.12, 0.25, 0.88]),
        "halation_threshold": 0.68,
        "vignette": 0.25, "bloom": 0.08,
        "border_text": "KODAK  EXR 5248",
        "film_format_mm": 35,
    },
    "5250": {
        "name": "Kodak 5250 (Daylight)",
        "category": "vintage_cinema",
        "description": "Vintage daylight cinema — softer, warmer than modern Vision3",
        "neg_data": sfl.KODAK_5250,
        "print_data": sfl.KODAK_5381,
        "exposure_kelvin": 5500, "exp_comp": 0.25, "sat": 1.0,
        "halation_strength": 0.08, "halation_radius": 0.04,
        "halation_color": np.array([0.12, 0.28, 0.90]),
        "halation_threshold": 0.68,
        "vignette": 0.28, "bloom": 0.10,
        "border_text": "KODAK  5250",
        "film_format_mm": 35,
    },
    "5277": {
        "name": "Kodak Vision 200T 5277",
        "category": "vintage_cinema",
        "description": "Early 2000s cinema tungsten — The Matrix, LOTR era",
        "neg_data": sfl.KODAK_5277,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 3200, "exp_comp": 0.3, "sat": 1.0,
        "halation_strength": 0.07, "halation_radius": 0.04,
        "halation_color": np.array([0.12, 0.25, 0.88]),
        "halation_threshold": 0.70,
        "vignette": 0.24, "bloom": 0.08,
        "border_text": "KODAK  5277  200T",
        "film_format_mm": 35,
    },
    "5293": {
        "name": "Kodak Vision 250D 5293",
        "category": "vintage_cinema",
        "description": "Early 2000s daylight cinema — warm, pre-Vision3 look",
        "neg_data": sfl.KODAK_5293,
        "print_data": sfl.KODAK_2383,
        "exposure_kelvin": 5500, "exp_comp": 0.25, "sat": 1.0,
        "halation_strength": 0.07, "halation_radius": 0.04,
        "halation_color": np.array([0.12, 0.28, 0.90]),
        "halation_threshold": 0.70,
        "vignette": 0.24, "bloom": 0.08,
        "border_text": "KODAK  5293  250D",
        "film_format_mm": 35,
    },

    # ── B&W ─────────────────────────────────────────────────────────────
    "trix400": {
        "name": "Kodak Tri-X 400",
        "category": "bw",
        "description": "Classic photojournalism — gritty, contrasty, iconic grain",
        "neg_data": sfl.KODAK_TRI_X_400,
        "print_data": sfl.KODAK_POLYMAX_GRADE_2,
        "exposure_kelvin": 5500, "exp_comp": 0.35, "sat": 1.0,
        # Tri-X: classic photojournalism — snappy contrast, visible grain, deep blacks
        "pre_flash_neg": -3.5, "black_offset": -1.5, "white_point": 0.93, "tint": 0,
        "halation_strength": 0.08, "halation_radius": 0.04,
        "halation_color": np.array([0.90, 0.90, 0.90]),
        "halation_threshold": 0.70,
        "vignette": 0.30, "bloom": 0.06,
        "border_text": "KODAK  TRI-X 400",
        "film_format_mm": 35,
    },
    "trix_push": {
        "name": "Kodak Tri-X 400 (Pushed)",
        "category": "bw",
        "description": "Pushed Tri-X — deep blacks, blown highlights, maximum drama",
        "neg_data": sfl.KODAK_TRI_X_400_DEV_9,
        "print_data": sfl.KODAK_POLYMAX_GRADE_3,
        "exposure_kelvin": 5500, "exp_comp": 0.5, "sat": 1.0,
        "halation_strength": 0.10, "halation_radius": 0.05,
        "halation_color": np.array([0.90, 0.90, 0.90]),
        "halation_threshold": 0.65,
        "vignette": 0.35, "bloom": 0.10,
        "border_text": "KODAK  TRI-X 400  PUSH",
        "film_format_mm": 35,
    },
    "doublex": {
        "name": "Kodak Double-X 5222",
        "category": "bw",
        "description": "Cinema B&W — Schindler's List, Raging Bull, Lighthouse",
        "neg_data": sfl.KODAK_5222,
        "print_data": sfl.KODAK_2302,
        "exposure_kelvin": 5500, "exp_comp": 0.3, "sat": 1.0,
        "halation_strength": 0.08, "halation_radius": 0.04,
        "halation_color": np.array([0.88, 0.88, 0.88]),
        "halation_threshold": 0.70,
        "vignette": 0.28, "bloom": 0.08,
        "border_text": "KODAK  5222  DOUBLE-X",
        "film_format_mm": 35,
    },
    "doublex_push": {
        "name": "Double-X 5222 (Pushed)",
        "category": "bw",
        "description": "Pushed cinema B&W — high contrast noir, The Lighthouse look",
        "neg_data": sfl.KODAK_5222_DEV_9,
        "print_data": sfl.KODAK_2302,
        "exposure_kelvin": 5500, "exp_comp": 0.5, "sat": 1.0,
        "halation_strength": 0.12, "halation_radius": 0.06,
        "halation_color": np.array([0.88, 0.88, 0.88]),
        "halation_threshold": 0.62,
        "vignette": 0.35, "bloom": 0.12,
        "border_text": "KODAK  5222  PUSH",
        "film_format_mm": 35,
    },
    "trix_soft": {
        "name": "Tri-X 400 (Soft Dev)",
        "category": "bw",
        "description": "Gentle development — lower contrast, more shadow detail",
        "neg_data": sfl.KODAK_TRI_X_400_DEV_7,
        "print_data": sfl.KODAK_POLYMAX_GRADE_1,
        "exposure_kelvin": 5500, "exp_comp": 0.25, "sat": 1.0,
        "halation_strength": 0.06, "halation_radius": 0.04,
        "halation_color": np.array([0.90, 0.90, 0.90]),
        "halation_threshold": 0.72,
        "vignette": 0.25, "bloom": 0.06,
        "border_text": "KODAK  TRI-X 400  SOFT",
        "film_format_mm": 35,
    },
    "trix_hard": {
        "name": "Tri-X 400 (Hard Push)",
        "category": "bw",
        "description": "Extreme push — crushed blacks, blown whites, punk zine aesthetic",
        "neg_data": sfl.KODAK_TRI_X_400_DEV_11,
        "print_data": sfl.KODAK_POLYMAX_GRADE_4,
        "exposure_kelvin": 5500, "exp_comp": 0.6, "sat": 1.0,
        "halation_strength": 0.14, "halation_radius": 0.06,
        "halation_color": np.array([0.90, 0.90, 0.90]),
        "halation_threshold": 0.58,
        "vignette": 0.40, "bloom": 0.14,
        "border_text": "KODAK  TRI-X 400  +3",
        "film_format_mm": 35,
    },
    "doublex_high_contrast": {
        "name": "Double-X (High Contrast)",
        "category": "bw",
        "description": "Extreme contrast cinema B&W — film noir, Sin City vibes",
        "neg_data": sfl.KODAK_5222_DEV_12,
        "print_data": sfl.KODAK_POLYMAX_GRADE_5,
        "exposure_kelvin": 5500, "exp_comp": 0.6, "sat": 1.0,
        "halation_strength": 0.15, "halation_radius": 0.07,
        "halation_color": np.array([0.88, 0.88, 0.88]),
        "halation_threshold": 0.55,
        "vignette": 0.42, "bloom": 0.16,
        "border_text": "KODAK  5222  HC",
        "film_format_mm": 35,
    },

    # ── Reversal / Slide Film ───────────────────────────────────────────
    "kodachrome64": {
        "name": "Kodachrome 64",
        "category": "reversal",
        "description": "Legendary — rich reds, deep shadows, the film of a generation",
        "neg_data": sfl.KODACHROME_64,
        "print_data": None,
        "exposure_kelvin": 5500, "exp_comp": -3.5, "sat": 1.08,
        # Kodachrome: DEEP rich reds, tight blacks, high contrast, legendary color
        "pre_flash_neg": -3.0, "black_offset": 0.5, "white_point": 0.97, "tint": 0,
        "halation_strength": 0.04, "halation_radius": 0.02,
        "halation_color": np.array([0.20, 0.30, 0.85]),
        "halation_threshold": 0.75,
        "vignette": 0.25, "bloom": 0.04,
        "border_text": "KODACHROME  64",
        "film_format_mm": 35,
    },
    "velvia50": {
        "name": "Fuji Velvia 50",
        "category": "reversal",
        "description": "Ultra-saturated slides — landscapes that pop off the screen",
        "neg_data": sfl.FUJI_VELVIA_50,
        "print_data": None,
        "exposure_kelvin": 5500, "exp_comp": -3.5, "sat": 1.15,
        # Velvia: INSANE saturation, deep contrast, landscape legend
        "pre_flash_neg": -3.0, "black_offset": 0.5, "white_point": 0.97, "tint": 0,
        "halation_strength": 0.04, "halation_radius": 0.02,
        "halation_color": np.array([0.18, 0.30, 0.88]),
        "halation_threshold": 0.75,
        "vignette": 0.22, "bloom": 0.04,
        "border_text": "FUJI  VELVIA 50",
        "film_format_mm": 35,
    },
    "provia100f": {
        "name": "Fuji Provia 100F",
        "category": "reversal",
        "description": "Neutral, accurate slide film — the pro standard",
        "neg_data": sfl.FUJI_PROVIA_100F,
        "print_data": None,
        "exposure_kelvin": 5500, "exp_comp": -3.5, "sat": 1.04,
        # Provia: neutral accurate slide — reversal needs negative exp_comp
        "pre_flash_neg": -3.0, "black_offset": 0.5, "white_point": 0.97, "tint": 0,
        "halation_strength": 0.04, "halation_radius": 0.02,
        "halation_color": np.array([0.20, 0.32, 0.85]),
        "halation_threshold": 0.75,
        "vignette": 0.22, "bloom": 0.04,
        "border_text": "FUJI  PROVIA 100F",
        "film_format_mm": 35,
    },
    "ektachrome": {
        "name": "Kodak Ektachrome 100D",
        "category": "reversal",
        "description": "Modern Kodak slide — cool tones, fine grain",
        "neg_data": sfl.KODAK_EKTACHROME_100D,
        "print_data": None,
        "exposure_kelvin": 5500, "exp_comp": -3.5, "sat": 1.04,
        # Ektachrome: cool Kodak slide — reversal needs negative exp_comp
        "pre_flash_neg": -3.0, "black_offset": 0.5, "white_point": 0.97, "tint": 0,
        "halation_strength": 0.04, "halation_radius": 0.02,
        "halation_color": np.array([0.18, 0.30, 0.88]),
        "halation_threshold": 0.75,
        "vignette": 0.22, "bloom": 0.04,
        "border_text": "KODAK  EKTACHROME 100D",
        "film_format_mm": 35,
    },

    # ── Instant & Experimental ──────────────────────────────────────────
    "fp100c": {
        "name": "Fuji FP-100C",
        "category": "instant",
        "description": "Peel-apart instant — creamy skin, dreamy greens, RIP legend",
        "neg_data": sfl.FUJI_FP100C,
        "print_data": None,
        "exposure_kelvin": 5500, "exp_comp": -3.0, "sat": 1.0,
        "halation_strength": 0.08, "halation_radius": 0.04,
        "halation_color": np.array([0.20, 0.35, 0.85]),
        "halation_threshold": 0.70,
        "vignette": 0.35, "bloom": 0.10,
        "border_text": "FUJI  FP-100C",
        "film_format_mm": 35,
    },
    "instax": {
        "name": "Fuji Instax Color",
        "category": "instant",
        "description": "Modern instant — slightly desaturated, nostalgic party photos",
        "neg_data": sfl.FUJI_INSTAX_COLOR,
        "print_data": None,
        "exposure_kelvin": 5500, "exp_comp": -3.0, "sat": 1.0,
        "halation_strength": 0.06, "halation_radius": 0.03,
        "halation_color": np.array([0.20, 0.32, 0.85]),
        "halation_threshold": 0.72,
        "vignette": 0.30, "bloom": 0.08,
        "border_text": "FUJI  INSTAX",
        "film_format_mm": 35,
    },
    "aerochrome": {
        "name": "Kodak Aerochrome III",
        "category": "instant",
        "description": "Infrared film — green becomes MAGENTA/RED, psychedelic landscapes",
        "neg_data": sfl.KODAK_AEROCHROME_III,
        "print_data": None,
        "exposure_kelvin": 5500, "exp_comp": -3.0, "sat": 1.05,
        "halation_strength": 0.12, "halation_radius": 0.05,
        "halation_color": np.array([0.05, 0.15, 1.0]),
        "halation_threshold": 0.65,
        "vignette": 0.30, "bloom": 0.10,
        "border_text": "KODAK  AEROCHROME III",
        "film_format_mm": 35,
    },
    # Cross-process: shooting negative film and processing as slide (or vice versa)
    "portra_xpro": {
        "name": "Portra 400 Cross-Process",
        "category": "instant",
        "description": "Portra neg with no print stage — shifted colors, experimental",
        "neg_data": sfl.KODAK_PORTRA_400,
        "print_data": None,
        "exposure_kelvin": 5500, "exp_comp": -3.0, "sat": 1.08,
        "halation_strength": 0.15, "halation_radius": 0.06,
        "halation_color": np.array([0.15, 0.30, 0.95]),
        "halation_threshold": 0.65,
        "vignette": 0.30, "bloom": 0.10,
        "border_text": "PORTRA 400  XPRO",
        "film_format_mm": 35,
    },
    "gold_xpro": {
        "name": "Gold 200 Cross-Process",
        "category": "instant",
        "description": "Gold negative-only — hyper warm, orange shadows, lo-fi",
        "neg_data": sfl.KODAK_GOLD_200,
        "print_data": None,
        "exposure_kelvin": 5500, "exp_comp": -3.0, "sat": 1.10,
        "halation_strength": 0.14, "halation_radius": 0.06,
        "halation_color": np.array([0.08, 0.25, 1.0]),
        "halation_threshold": 0.62,
        "vignette": 0.38, "bloom": 0.12,
        "border_text": "GOLD 200  XPRO",
        "film_format_mm": 35,
    },
    "cinestill_xpro": {
        "name": "Cinestill 800T Cross-Process",
        "category": "instant",
        "description": "Vision3 500T negative-only — blue cast, halation, cyberpunk",
        "neg_data": sfl.KODAK_5219,
        "print_data": None,
        "exposure_kelvin": 3200, "exp_comp": -3.0, "sat": 1.0,
        "halation_strength": 0.60, "halation_radius": 0.12,
        "halation_color": np.array([0.02, 0.08, 1.0]),
        "halation_threshold": 0.40,
        "vignette": 0.28, "bloom": 0.18,
        "border_text": "CINESTILL 800T  XPRO",
        "film_format_mm": 35,
    },
}

# Cache for built conversions
_built_stocks = {}


def _build_stock(key):
    """Lazily build the conversion for a stock on first use."""
    if key in _built_stocks:
        return _built_stocks[key]

    defn = _STOCK_DEFS[key]
    conv, neg = make_conversion(
        defn["neg_data"], defn["print_data"],
        exposure_kelvin=defn["exposure_kelvin"],
        exp_comp=defn["exp_comp"],
        sat=defn["sat"],
        pre_flash_neg=defn.get("pre_flash_neg", -4),
        black_offset=defn.get("black_offset", 0),
        white_point=defn.get("white_point", 1.0),
        tint=defn.get("tint", 0),
    )
    stock = {
        "name": defn["name"],
        "category": defn["category"],
        "description": defn["description"],
        "conv": conv,
        "neg": neg,
        "halation_strength": defn["halation_strength"],
        "halation_radius": defn["halation_radius"],
        "halation_color": defn["halation_color"],
        "halation_threshold": defn["halation_threshold"],
        "vignette": defn["vignette"],
        "bloom": defn["bloom"],
        "border_text": defn["border_text"],
        "film_format_mm": defn["film_format_mm"],
        "neg_data": defn["neg_data"],
        "print_data": defn["print_data"],
        "exposure_kelvin": defn["exposure_kelvin"],
        "exp_comp": defn["exp_comp"],
        "sat": defn["sat"],
    }
    _built_stocks[key] = stock
    return stock


def build_custom_stock(key, print_stock_data=None, exp_comp=None, sat=None,
                       pre_flash_neg=-4, pre_flash_print=-4,
                       black_offset=0, white_point=1.0, tint=0):
    """Build a stock with custom print pairing or quality parameters."""
    defn = _STOCK_DEFS[key]
    pdata = print_stock_data if print_stock_data is not None else defn["print_data"]
    ec = exp_comp if exp_comp is not None else defn["exp_comp"]
    s = sat if sat is not None else defn["sat"]

    conv, neg = make_conversion(
        defn["neg_data"], pdata,
        exposure_kelvin=defn["exposure_kelvin"],
        exp_comp=ec, sat=s,
        pre_flash_neg=pre_flash_neg, pre_flash_print=pre_flash_print,
        black_offset=black_offset, white_point=white_point, tint=tint,
    )
    stock = {
        "name": defn["name"],
        "category": defn["category"],
        "description": defn["description"],
        "conv": conv,
        "neg": neg,
        "halation_strength": defn["halation_strength"],
        "halation_radius": defn["halation_radius"],
        "halation_color": defn["halation_color"],
        "halation_threshold": defn["halation_threshold"],
        "vignette": defn["vignette"],
        "bloom": defn["bloom"],
        "border_text": defn["border_text"],
        "film_format_mm": defn["film_format_mm"],
    }
    return stock


def get_stock(key):
    """Get a built stock by key. Lazily initializes on first call."""
    if key not in _STOCK_DEFS:
        raise KeyError(f"Unknown stock: {key}")
    return _build_stock(key)


def get_all_stocks():
    """Return metadata for all stocks (without building conversions)."""
    return {
        key: {
            "name": defn["name"],
            "category": defn["category"],
            "description": defn["description"],
        }
        for key, defn in _STOCK_DEFS.items()
    }


def get_stocks_by_category():
    """Return stocks grouped by category (metadata only)."""
    result = {cat: [] for cat in CATEGORIES}
    for key, defn in _STOCK_DEFS.items():
        result[defn["category"]].append({
            "key": key,
            "name": defn["name"],
            "description": defn["description"],
        })
    return result
